version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mean_mongo
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: mean_backend
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mean_db

  frontend:
    build: ./frontend
    container_name: mean_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: